Repository Abbhiishek/Webners, pull requests merged in 2022-10, with the labels that each got.

#6 added hotel website
  CONTRIBUTORS.json
  Contributions/Hotel-website/Preview.png
  Contributions/Hotel-website/README.md
  Contributions/Hotel-website/clean.css
  Contributions/Hotel-website/images/DELHI.jpg
  Contributions/Hotel-website/images/Goa.jpg
  Contributions/Hotel-website/images/Udaipur.jpg
  Contributions/Hotel-website/images/background-img-1.jpg
  Contributions/Hotel-website/images/cancel-icici-bank-credit-card.webp
  Contributions/Hotel-website/images/del hotel.jpg
  Contributions/Hotel-website/images/fifty.png
  Contributions/Hotel-website/images/hotelimage.png
  Contributions/Hotel-website/images/icici.png
  Contributions/Hotel-website/images/img.jpg
  Contributions/Hotel-website/images/img1.jpg
  Contributions/Hotel-website/images/img3.jpg
  Contributions/Hotel-website/images/img4.jpeg
  Contributions/Hotel-website/images/jaipur.jpg
  Contributions/Hotel-website/images/luxury.jpg
  Contributions/Hotel-website/images/makemytrip_425_735_425_735.jpg
  Contributions/Hotel-website/images/phone-call.png
  Contributions/Hotel-website/images/phone.png
  Contributions/Hotel-website/images/the-park-new-delhi.jpg
  Contributions/Hotel-website/index.html
  Contributions/Hotel-website/style.css
  Contributions/Hotel-website/telephone.png
Labels: enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#17 Todo Application Initials
  CONTRIBUTORS.json
  Contributions/todocp/README.md
  Contributions/todocp/index.html
  Contributions/todocp/script.js
  Contributions/todocp/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#10 GitHub worklfow greeting
  .github/workflows/greetings.yml
Labels: documentation, enhancement, hacktoberfest-accepted

#13 Product Preview Card Component
  CONTRIBUTORS.json
  Contributions/Product Preview Card Component/README.md
  Contributions/Product Preview Card Component/design/active-states.jpg
  Contributions/Product Preview Card Component/design/desktop-design.jpg
  Contributions/Product Preview Card Component/design/desktop-preview.jpg
  Contributions/Product Preview Card Component/design/mobile-design.jpg
  Contributions/Product Preview Card Component/images/favicon-32x32.png
  Contributions/Product Preview Card Component/images/icon-cart.svg
  Contributions/Product Preview Card Component/images/image-product-desktop.jpg
  Contributions/Product Preview Card Component/images/image-product-mobile.jpg
  Contributions/Product Preview Card Component/index.html
  Contributions/Product Preview Card Component/style.css
Labels: hacktoberfest, hacktoberfest-accepted

#25 init ☄️
  .gitignore
  index.html
  package-lock.json
  package.json
  postcss.config.cjs
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/index.css
  src/main.jsx
  tailwind.config.cjs
  vite.config.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#30 Rudresh
  CONTRIBUTORS.json
  Contributions/Put_Your_Pass/README.md
  Contributions/Put_Your_Pass/index.html
  Contributions/Put_Your_Pass/script.js
  Contributions/Put_Your_Pass/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#43 Contribution badge
  CONTRIBUTORS.json
  README.md
Labels: hacktoberfest-accepted

#50 Adding responsiveness and local storage
  Contributions/Put_Your_Pass/index.html
  Contributions/Put_Your_Pass/script.js
  Contributions/Put_Your_Pass/style.css
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#53 Added my pizza corner website
  CONTRIBUTORS.json
  Contributions/pizza corner/background.jpg
  Contributions/pizza corner/bacon.jpg
  Contributions/pizza corner/chilli.jpg
  Contributions/pizza corner/crispychicken.jpg
  Contributions/pizza corner/index.html
  Contributions/pizza corner/margherita.webp
  Contributions/pizza corner/readme.md
  Contributions/pizza corner/shrimppizza.jpg
  Contributions/pizza corner/style.css
  Contributions/pizza corner/veg.jpg
Labels: hacktoberfest, hacktoberfest-accepted

#59 my details changed :)
  CONTRIBUTORS.json
Labels: hacktoberfest, hacktoberfest-accepted

#61 username was not present for one entry :)
  CONTRIBUTORS.json
Labels: hacktoberfest, hacktoberfest-accepted

#62 Beluga2003 patch 2
  src/App.jsx
  src/components/ContributorCard.jsx
Labels: hacktoberfest-accepted
